#!/bin/bash

##  SPDX-FileCopyrightText: © 2023 Remo Dentato <rdentato@gmail.com>
##  SPDX-License-Identifier: MIT

usage () {
  echo "Usage:"
  echo "   tstrun [options] [wildcard] [tags]"
  echo ""
  echo "OPTIONS"
  echo "  -h | --help                 this help"
  echo "  -l | --list                 prints the list of available tests"
  echo "  -d | --test-directory dir   cd to the directory dir with tests"
  echo "  -w | --wildcard '*x[yz]'    specify a file pattern to match the tests to execute"
  echo "  -o | --output filename      the name of the generated logfile"
  echo ""
  echo "WILDCARD"
  echo "  A filter to select which tests to run ('*' by default). Note that it MUST be"
  echo "  single quoted to prevent shell expansion. The initial 't_' is implied."
  echo ""
  echo "TAGS"
  echo "  [+/-]tagname to turn the tag on/off"
  exit 1
}

WILDCARD="*"
OUTFILE="test.log"
TAGS=""

COLOR_TOGGLE=1
DEFAULT_OPTIONS=0

if [ "$TSTOPTIONS" != "" ] ; then
  set -- $TSTOPTIONS "@@" "$@"
  DEFAULT_OPTIONS=1
fi

while [ "$#" -gt 0 ]; do
  case $1 in 

   -h | --help) 
      usage ;;

   -l | --list)
      find . -name "t_$WILDCARD" -print | sed -e '/\.c$/d' -e '/\.cpp$/d' -e '/\.o$/d' | while read -r f ; do $f --l ; done
      exit 0 ;;

   -w | --wildcard)
      shift
      if [ "$#" -eq 0 ]; then echo "ERROR: Missing wildcard"; usage ; fi
      WILDCARD=$1
      shift ;;

   -d | --test-directory)
      shift
      if [ "$#" -eq 0 ]; then echo "ERROR: Missing directory"; usage ; fi
      cd $1
      shift ;;

   @@)
      DEFAULT_OPTIONS=0
      shift
      ;;

    -o | --output)
      shift;
      if [ "$#" -eq 0 ]; then echo "ERROR: Missing output file name"; usage ; fi
      OUTFILE=$1;
      shift ;;

    --*) echo "Invalid option $1"; usage ;;

    +*|-*) 
        if [ $DEFAULT_OPTIONS -eq 0 ] ; then break ; fi
        TAGS="$TAGS $1" #collect tags that may be in default options
        shift
        ;;

    *)  WILDCARD=$1
        shift
        break;
        ;;
  esac
done

echo "output: $OUTFILE ($WILDCARD)"
echo "STIME `date`" > $OUTFILE
find . -name "t_$WILDCARD" -print | sed -e '/\.c$/d' -e '/\.cpp$/d' -e '/\.o$/d' | while read -r f ; do $f $TAGS $* ; done 2>> $OUTFILE

FAIL=`grep '^[0-9 ]*FAIL' $OUTFILE | wc -l`
PASS=`grep '^[0-9 ]*PASS' $OUTFILE | wc -l`
SKIP=`grep '^[0-9 ]*SKIP' $OUTFILE | wc -l`

echo "TOTAL $FAIL FAIL | $PASS PASS | $SKIP SKIP" >> $OUTFILE

echo "ETIME `date`" >> $OUTFILE
